import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Camera, Save } from 'lucide-react';
import { FederalOfficialTitle, FederalOfficialTitles } from '../types';
import { LicenseService } from '../services/licenseService';
import { FederalOfficialService } from '../services/federalOfficialService';

const tomorrowYear = () => { const date = new Date(); date.setFullYear(date.getFullYear() + 1); return date.toISOString().slice(0, 10); };
export const FederalOfficialForm: React.FC = () => {
  const { id } = useParams(); const navigate = useNavigate(); const [loading, setLoading] = useState(false); const [photo, setPhoto] = useState<File | null>(null); const [preview, setPreview] = useState('');
  const [data, setData] = useState({ title: '' as FederalOfficialTitle | '', firstName: '', lastName: '', birthDate: '', nationality: 'Sénégalaise', address: '', phone: '', email: '', issueDate: new Date().toISOString().slice(0, 10), expirationDate: tomorrowYear(), photoUrl: '', photoPositionX: 50, photoPositionY: 50 });
  useEffect(() => { if (!LicenseService.isAuthenticated()) { navigate('/login'); return; } if (id) FederalOfficialService.getById(id).then(value => { const { id: _id, createdAt: _createdAt, photoUrl, photoPositionX, photoPositionY, ...fields } = value; setData({ ...fields, photoUrl: photoUrl || '', photoPositionX: photoPositionX ?? 50, photoPositionY: photoPositionY ?? 50 }); setPreview(photoUrl || ''); }).catch(() => navigate('/admin/cadres-federaux')); }, [id, navigate]);
  const onPhoto = (file?: File) => { if (!file) return; if (!file.type.startsWith('image/')) return alert('Veuillez choisir une image.'); if (file.size > 2 * 1024 * 1024) return alert('La photo doit faire moins de 2 Mo.'); setPhoto(file); setPreview(URL.createObjectURL(file)); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { let photoUrl = data.photoUrl; if (photo) photoUrl = await LicenseService.uploadPhoto(photo); const payload = { ...data, title: data.title as FederalOfficialTitle, photoUrl }; if (id) await FederalOfficialService.update(id, payload); else await FederalOfficialService.create(payload); navigate('/admin/cadres-federaux'); } catch (error: any) { alert(error.message || 'Enregistrement impossible'); } finally { setLoading(false); } };
  const input = 'w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-2.5 outline-none focus:border-fss-green focus:ring-2 focus:ring-fss-green/20'; const label = 'mb-1.5 block text-xs font-bold uppercase tracking-wider text-slate-500';
  return <div className="min-h-screen bg-slate-50 pb-16"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button onClick={() => navigate('/admin/cadres-federaux')} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100"><ArrowLeft size={20} /></button><div><h1 className="text-xl font-bold">{id ? 'Modifier le cadre fédéral' : 'Nouveau cadre fédéral'}</h1><p className="text-xs text-slate-500">Carte professionnelle FSS</p></div></div><button form="official-form" disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-fss-green px-5 py-2.5 font-bold text-white disabled:opacity-60"><Save size={17} /> {loading ? 'Enregistrement…' : 'Enregistrer'}</button></header>
    <form id="official-form" onSubmit={submit} className="mx-auto grid max-w-5xl grid-cols-1 gap-8 px-5 py-10 lg:grid-cols-3 sm:px-8"><aside className="space-y-6"><div className="premium-card p-6 text-center"><label className={label}>Photo officielle</label><label className="relative mx-auto mt-4 flex h-48 w-48 cursor-pointer items-center justify-center overflow-hidden rounded-3xl border-4 border-white bg-slate-100 shadow-xl">{preview ? <img src={preview} alt="Aperçu" className="h-full w-full object-cover" style={{ objectPosition: `${data.photoPositionX}% ${data.photoPositionY}%` }} /> : <span className="flex flex-col items-center gap-2 text-slate-400"><Camera size={38} /><span className="text-[10px] font-bold uppercase">Ajouter une photo</span></span>}<input type="file" accept="image/*" onChange={e => onPhoto(e.target.files?.[0])} className="absolute inset-0 cursor-pointer opacity-0" /></label><p className="mt-5 text-xs text-slate-400">JPG, PNG ou WebP · 2 Mo max.</p>{preview && <div className="mt-5 space-y-4 text-left"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Cadrage de la photo</p><div><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Horizontal</span><span>{data.photoPositionX}%</span></div><input aria-label="Position horizontale de la photo" type="range" min="0" max="100" value={data.photoPositionX} onChange={e => setData({ ...data, photoPositionX: Number(e.target.value) })} className="w-full accent-fss-green" /></div><div><div className="mb-1 flex justify-between text-xs text-slate-500"><span>Vertical</span><span>{data.photoPositionY}%</span></div><input aria-label="Position verticale de la photo" type="range" min="0" max="100" value={data.photoPositionY} onChange={e => setData({ ...data, photoPositionY: Number(e.target.value) })} className="w-full accent-fss-green" /></div></div>}</div><div className="premium-card space-y-4 p-6"><div><label className={label}>Date d'émission</label><input required type="date" value={data.issueDate} onChange={e => setData({ ...data, issueDate: e.target.value })} className={input} /></div><div><label className={label}>Date d'expiration</label><input required type="date" value={data.expirationDate} onChange={e => setData({ ...data, expirationDate: e.target.value })} className={input} /></div></div></aside>
      <main className="space-y-6 lg:col-span-2"><section className="premium-card p-7"><h2 className="mb-6 text-lg font-bold">Fonction et identité</h2><div className="grid grid-cols-1 gap-5 md:grid-cols-2"><div className="md:col-span-2"><label className={label}>Fonction fédérale</label><select required value={data.title} onChange={e => setData({ ...data, title: e.target.value as FederalOfficialTitle | '' })} className={input}><option value="" disabled>Choisir une fonction...</option>{FederalOfficialTitles.map(title => <option key={title}>{title}</option>)}</select></div><div><label className={label}>Prénom</label><input required value={data.firstName} onChange={e => setData({ ...data, firstName: e.target.value })} className={input} /></div><div><label className={label}>Nom</label><input required value={data.lastName} onChange={e => setData({ ...data, lastName: e.target.value })} className={input} /></div><div><label className={label}>Date de naissance</label><input required type="date" value={data.birthDate} onChange={e => setData({ ...data, birthDate: e.target.value })} className={input} /></div><div><label className={label}>Nationalité</label><input required value={data.nationality} onChange={e => setData({ ...data, nationality: e.target.value })} className={input} /></div></div></section><section className="premium-card p-7"><h2 className="mb-6 text-lg font-bold">Coordonnées</h2><div className="grid grid-cols-1 gap-5 md:grid-cols-2"><div><label className={label}>Téléphone</label><input required type="tel" value={data.phone} onChange={e => setData({ ...data, phone: e.target.value })} className={input} placeholder="+221 …" /></div><div><label className={label}>Email</label><input required type="email" value={data.email} onChange={e => setData({ ...data, email: e.target.value })} className={input} /></div><div className="md:col-span-2"><label className={label}>Adresse</label><input required value={data.address} onChange={e => setData({ ...data, address: e.target.value })} className={input} /></div></div></section></main></form></div>;
};
