-- Persist the club catalogue independently from licenses, so a custom club
-- remains available in future dropdowns.
CREATE TABLE IF NOT EXISTS clubs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(trim(name)) > 0),
  normalized_name text NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE clubs ENABLE ROW LEVEL SECURITY;

-- The API uses the service role and bypasses RLS. This policy keeps the
-- catalogue readable if a public client needs it later.
CREATE POLICY "Public Read Access" ON clubs
  FOR SELECT USING (true);

INSERT INTO clubs (name, normalized_name)
VALUES
  ('SURF CLUB NGOR', 'SURF CLUB NGOR'),
  ('TAKE OFF NGOR', 'TAKE OFF NGOR'),
  ('HAPPY SECRET GARDEN', 'HAPPY SECRET GARDEN'),
  ('MALIKA SURF', 'MALIKA SURF'),
  ('COPACABANA SURF VILLAGE', 'COPACABANA SURF VILLAGE'),
  ('SURF ATTITUDE', 'SURF ATTITUDE'),
  ('SOMONE SURF', 'SOMONE SURF'),
  ('BLACK AND WHITE', 'BLACK AND WHITE')
ON CONFLICT (normalized_name) DO NOTHING;

INSERT INTO clubs (name, normalized_name)
SELECT DISTINCT ON (normalized_name) name, normalized_name
FROM (
  SELECT
    CASE
      WHEN upper(trim(club)) = 'TAKEOFF NGOR' THEN 'TAKE OFF NGOR'
      ELSE trim(club)
    END AS name,
    CASE
      WHEN upper(trim(club)) = 'TAKEOFF NGOR' THEN 'TAKE OFF NGOR'
      ELSE upper(trim(club))
    END AS normalized_name
  FROM licenses
  WHERE club IS NOT NULL AND trim(club) <> ''
) license_clubs
ON CONFLICT (normalized_name) DO NOTHING;
